import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeWrapper from "../components/ThemeWrapper";
import { AuthProvider } from "../components/AuthProvider";
import { TicketsProvider } from "../components/TicketsProvider";
import Header from "../components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "TICKEDU",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
        <ThemeWrapper>
          <AuthProvider>
            <TicketsProvider>
              <Header />
              {children}
            </TicketsProvider>
          </AuthProvider>
        </ThemeWrapper>
      </body>
    </html>
  );
}
